site_name: Komodor
strict: true
site_url: "https://docs.komodor.com"
repo_url: https://github.com/komodorio/docs
repo_name: komodorio/docs
edit_uri: https://github.com/komodorio/docs/edit/main/docs/getting-started.md
use_directory_urls: false
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
  favicon: "img/favicon.png"
  palette:
    primary: indigo
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
extra:
  homepage: https://docs.komodor.com/
nav:
  - Home: index.md
  - Learn:
      - Install the agent: Learn/Install-Komodor-Agent.md
      - Komodor's Agent: Learn/Komodor-Agent.md
      - Annotations: Learn/Annotations.md
      - Monitors: Learn/Monitors.md
      - Config Changes: Learn/config-changes.md
      - External Links: Learn/ExternalLinks.md
      - Source Control: Learn/komodor-source-control.md
      - Sensitive Information Redaction: Learn/Sensitive-Information-Redaction.md
      - Interaction with the Cluster: Learn/Interaction-With-The-Cluster.md
      - Manage Users: Learn/ManageUsers.md
      - RBAC: Learn/RBAC.md
      - Static Prevention: Learn/Static-Prevention.md
      - Actions:
          - Overview: Learn/Actions/Overview.md
          - Pod Shell: Learn/Actions/PodExec.md
      - Helm: Learn/Helm.md
      - Metrics: Learn/Metrics.md
      - Test Utilities Commands: Learn/Test-Utilities-Commands.md
  - Integrations:
      - Datadog: Integrations/Datadog.md
      - Datadog Webhook: Integrations/datadog-webhook.md
      - Datadog Monitor Notifications: Integrations/Datadog-Monitor-Notification.md
      - LaunchDarkly: Integrations/LaunchDarkly.md
      - Opsgenie: Integrations/Opsgenie.md
      - PagerDuty: Integrations/PagerDuty.md
      - Sentry: Integrations/Sentry.md
      - Slack: Integrations/Slack.md
      - Microsoft Teams: Integrations/MicrosoftTeams.md
      - Okta:
          - Okta SSO (SAML): Integrations/Okta/Okta.md
          - Role Provisioning (Okta): Integrations/Okta/Okta-Role-Provisioning.md
      - Azure Active Directory: Integrations/AzureActiveDirectory.md
      - Grafana / Alert Manager: Integrations/AlertManager.md
      - ArgoCD: Integrations/ArgoCD.md
      - Webhook: Integrations/Webhook.md
      - Loft: Integrations/Loft.md
      - Squadcast: Integrations/Squadcast.md
  - Komodor API: openapi/redoc-static.html
