site_name: Komodor 
strict: true
site_url: "https://www.komodor.com/docs"
repo_url: https://github.com/komodorio/docs
repo_name: komodorio/docs
edit_uri: https://github.com/komodorio/docs/edit/main/docs/getting-started.md
use_directory_urls: false
theme:
  name: material
  custom_dir: overrides 
  language: en
  features:
    - navigation.tabs
  favicon: 'img/favicon.png'
  palette:
    primary: indigo 
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
extra:
  homepage: https://www.komodor.com
nav:
  - Home: index.md
  - Learn:
    - Komodor's Agent: Learn/Komodor-Agent.md
    - Annotations: Learn/Annotations.md
    - Config Changes: Learn/config-changes.md
    - Source Control: Learn/komodor-source-control.md
    - Sensitive Information Redaction: Learn/Sensitive-Information-Redaction.md
    - Interaction with the Cluster: Learn/Interaction-With-The-Cluster.md
    - Manage Users: Learn/ManageUsers.md
    - RBAC: Learn/RBAC.md
  - Integrations:
    - Datadog: Integrations/Datadog.md
    - Datadog Webhook: Integrations/datadog-webhook.md
    - Datadog Monitor Notifications: Integrations/Datadog-Monitor-Notification.md 
    - Grafana: Integrations/Grafana.md
    - LaunchDarkly: Integrations/LaunchDarkly.md
    - PagerDuty: Integrations/PagerDuty.md
    - Sentry: Integrations/Sentry.md
    - Microsoft Teams: Integrations/MicrosoftTeams.md
    - Okta: Integrations/Okta/Okta.md
  - Komodor API: openapi/redoc-static.html